server:
  port: 8282
spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      globalcors:
        cors-configuration:
          '[/**]':
            allowedOrigins:
              - "localhost:4200"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
        routes:
          - id: ms-customer
            uri: lb://ms-customer
            predicates:
              - Path=/api/customer/**
            filters:
              - RewritePath=/ms-customer/(?<path>.*), /$\{path}
          - id: ms-account
            uri: lb://ms-account
            predicates:
              - Path=/api/account/**
            filters:
              - RewritePath=/ms-account/(?<path>.*), /$\{path}
      # Automatic discovery of services
      #discovery:
      #  locator:
      #    enabled: true
      #    lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: gateway

eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
